In [7]:
import numpy as np

In [8]:
x=np.arange(10).reshape(5,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
y=range(5)
y

range(0, 5)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test=train_test_split(x,y)


In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
model= LinearRegression()

In [14]:
model.fit(x_train,y_train)

LinearRegression()

In [15]:
model.predict(x_test)

array([3.00000000e+00, 4.16333634e-16])

In [16]:
y_test

[3, 0]

In [17]:
import pickle

with open('LRmodel.pkl','wb') as f:
    pickle.dump(model,f)

In [18]:
with open('LRmodel.pkl','rb') as f:
    saved_model=pickle.load(f)

In [19]:
saved_model

LinearRegression()

In [20]:
saved_model.predict([[10,11]])

array([5.])

In [21]:
import joblib
file='LR_model.sav'
joblib.dump(model,file)

joblib_model=joblib.load(file)

joblib_model.predict([[10,11]])

array([5.])