In [3]:
import numpy as np

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(1)

array([0.22972738])

In [12]:
np.random.randn(25)

array([-1.75009721,  0.85701076, -1.04591162,  0.09730988, -0.83790245,
        1.21189221, -1.2643442 ,  2.2582794 , -0.85173898,  0.24992012,
       -0.29729177, -0.60055176,  0.13195492, -0.62915113, -0.33144269,
       -1.46396111, -0.74224844,  0.43008547, -1.36478325, -0.5265967 ,
       -1.0570171 , -0.88538443, -1.29333276,  0.70817156,  1.02152673])

In [13]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [14]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [2]:
import numpy as np
a=np.arange(1,26).reshape(5,5)


In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [5]:
a[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [6]:
a[3,4]

20

In [7]:
a[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [8]:
a[4:]

array([[21, 22, 23, 24, 25]])

In [9]:
a[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
a.sum() #sum of matrix

325

In [11]:
a.std() #standard deviation

7.211102550927978

In [12]:
a.sum(axis=0)#sum of columns

array([55, 60, 65, 70, 75])

In [16]:
a.var(axis=1) #sum of rows

array([2., 2., 2., 2., 2.])

In [27]:
d=np.arange(16)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
b=np.arange(16).reshape(4,4)

In [29]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
c=np.arange(1,13).reshape(3,2,2)

In [31]:
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [32]:
b.dtype

dtype('int32')

In [33]:
c.dtype

dtype('int32')

In [34]:
d.shape

(16,)

In [35]:
b.shape

(4, 4)

In [36]:
c.shape

(3, 2, 2)

In [37]:
b.ndim

2

In [38]:
c.ndim

3

In [116]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [117]:
np.ones(16).reshape(4,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
maths_marks=np.random.randint(1,100,20)
maths_marks

array([31, 72, 77, 76, 15, 73,  5, 79, 57, 30, 80, 76, 23, 31, 31, 38, 72,
       16, 42, 89])

In [28]:
m=np.sort(maths_marks)
m

array([ 5, 15, 16, 23, 30, 31, 31, 31, 38, 42, 57, 72, 72, 73, 76, 76, 77,
       79, 80, 89])

In [26]:
asc=m
np.flip(asc)

array([89, 80, 79, 77, 76, 76, 73, 72, 72, 57, 42, 38, 31, 31, 31, 30, 23,
       16, 15,  5])

In [1]:
import numpy as np


f = np.array([1, 2, 3, 4, 5])


g = np.copy(f)
f
g


array([1, 2, 3, 4, 5])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
np.eye(5).resha pe(25)
#.ravel
#.flatten

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [63]:
mat=np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
np.append(mat,[[9,10,11]],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [72]:
x=mat
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
np.split(x,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [74]:
v=mat
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
np.split(v,3,axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [80]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [2]:
import numpy as np
np.random.uniform?

In [91]:
s = np.random.uniform(1,9,10)
s

array([8.26160491, 6.43239127, 3.63510817, 1.10864567, 1.30122474,
       5.32538152, 5.39693561, 4.4769029 , 8.4242846 , 6.81592941])

In [92]:
np.ceil(s)

array([9., 7., 4., 2., 2., 6., 6., 5., 9., 7.])

In [93]:
np.floor(s)

array([8., 6., 3., 1., 1., 5., 5., 4., 8., 6.])

In [96]:
np.round(s,decimals=2)

array([8.26, 6.43, 3.64, 1.11, 1.3 , 5.33, 5.4 , 4.48, 8.42, 6.82])

In [99]:
q=np.arange(0,25).reshape(5,5)
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [104]:
q.min(axis=0)

array([0, 1, 2, 3, 4])

In [107]:
q.max(axis=0)

array([20, 21, 22, 23, 24])

In [108]:
q.std(axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [110]:
q.var(axis=0)

array([50., 50., 50., 50., 50.])

In [2]:
import numpy as np

r = np.zeros(10)

r[5] = 200

r

array([  0.,   0.,   0.,   0.,   0., 200.,   0.,   0.,   0.,   0.])

In [112]:
af=np.arange(100,151)
af

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [113]:
np.flip(af)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [114]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
fa=(1,0,2,0,0,4,0,8)
fa

(1, 0, 2, 0, 0, 4, 0, 8)

In [119]:
np.nonzero(fa)

(array([0, 2, 5, 7], dtype=int64),)

In [124]:
afk=np.ones((10,10))

In [127]:
afk[1:9,1:9]=0
afk

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
import numpy as np
n=np.zeros((8,8))
n[::2,::2]=1
n[1::2,1::2]=1
n

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
import numpy as np
a=np.zeros((8,8))
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
a[1:7,1:7]=1
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
import numpy as np

l= np.random.randint(1, 10, size=(3, 3))
k= np.random.randint(1, 10, size=(3, 3))


addition = np.add(l, k)
print("\nAddition:")
print(addition)


subtraction = np.subtract(l, k)
print("\nSubtraction:")
print(subtraction)


multiplication = np.dot(l, k)
print("\nMultiplication:")
print(multiplication)



Addition:
[[14  8  9]
 [14  8  8]
 [16  6 14]]

Subtraction:
[[-2 -2  7]
 [ 4  6 -4]
 [ 2 -4 -4]]

Multiplication:
[[119  73  96]
 [121  62  69]
 [112  71  60]]


In [28]:
z=np.linspace(30,60,10)
z

array([30.        , 33.33333333, 36.66666667, 40.        , 43.33333333,
       46.66666667, 50.        , 53.33333333, 56.66666667, 60.        ])

In [30]:
np.ceil(z)

array([30., 34., 37., 40., 44., 47., 50., 54., 57., 60.])

In [31]:
np.floor(z)

array([30., 33., 36., 40., 43., 46., 50., 53., 56., 60.])

In [32]:
np.round(z)

array([30., 33., 37., 40., 43., 47., 50., 53., 57., 60.])

In [34]:
w=np.arange(10,20,2)
w

array([10, 12, 14, 16, 18])